---
- name: load subnet variables
  include_vars: "{{ playbook_dir }}/group_vars/lab_specifics.yml"
  run_once: true

- name: Deleting user / assigning project
  os_user:
    cloud: cloud-admin
    state: '{{ state }}'
    name: '{{ item.user_name }}'
  with_items: "{{ projects }}"
  loop_control:
    label: "{{ item.name }}"

- name: Deleting project
  os_project:
    cloud: cloud-admin
    state: '{{ state }}'
    name: '{{ item.name }}'
  with_items: "{{ projects }}"
  loop_control:
    label: "{{ item.name }}"
