---
# cleanup br-tun before we restart neutron
- name: Removing br-tun so openstack recreates it
  openvswitch_bridge: bridge=br-tun state=absent

- name: adding the MTU in neutron.conf
  ini_file: dest=/etc/neutron/neutron.conf section=DEFAULT option=global_physnet_mtu value={{ mtu }} backup=yes

- name: Starting libvirtd
  service:
    name=libvirtd
    state=started
    enabled=yes
  ignore_errors: true

- name: setting theme for horizon
  lineinfile:
    dest=/etc/openstack-dashboard/local_settings
    regexp='CUSTOM_THEME_PATH'
    line='CUSTOM_THEME_PATH = 'themes/material''
    state=present
  notify:
    - restart httpd
  when:
    - inventory_hostname in groups.controller
  tags:
    - theme

- name: reboot
  command: systemd-run --on-active=10 systemctl reboot
  async: 0
  poll: 0
  tags:
    - reboot

- name: Waiting for blade to come back after installation reboot
  become: false
  local_action:
    wait_for
      host={{ inventory_hostname }}
      state=started
      port=22
      delay=60
      timeout=400
  tags:
    - reboot
