#!/usr/bin/ansible-playbook
---
- hosts: [additional_compute]
  remote_user: root
  connection: local
  roles:
    - { role: generate_vars, tags: vars }    
    - { role: pxe, tags: pxe }    

# openstack prep
- hosts: [additional_compute]
  gather_facts: no
  roles:
    - { role: repave, tags: repave }

- hosts: [additional_compute]
  gather_facts: no
  roles:
    - { role: expose_repos, tags: expose_repos }

# start customizing systems based on lab specifics
- hosts: [additional_compute]
  gather_facts: no
  roles:
    - { role: lab_custom, tags: lab_custom }
    - { role: prime_os, tags: prime_os }
    - { role: prepare_openstack, tags: prepare_openstack }
    - { role: change_kernel, tags: change_kernel }
  #environment:  
    #http_proxy: http://www-proxy.us.oracle.com:80

- hosts: [additional_compute]
  gather_facts: no
  roles:
    - { role: distribute_controller_key, tags: distribute_controller_key }
    - { role: hack_chkconfig, tags: hack_chkconfig }

- hosts: [additional_compute]
  tasks:
     - name: Run Packstack Manually
       pause: 

###
- hosts: [controller]
  roles:
    - { role: install_openstack_for_additional_compute, tags: install_openstack_for_additional_compute }

- hosts: [controller]
  roles:
     - { role: run_packstack_for_additional_compute, tags: run_packstack_for_additional_compute }
###

- hosts: [additional_compute]
  roles:
     - { role: unhack_chkconfig, tags: unhack_chkconfig }
     - { role: ovs_interfaces, tags: ovs_interfaces }

# openstack post-installation and customization
- hosts: [additional_compute]
  roles:
    - { role: post_packstack_nova, tags: post_packstack_nova }

- hosts: [additional_compute]
  roles:
    - { role: post_packstack_neutron_compute, tags: post_packstack_neutron_compute }

- hosts: [additional_compute]
  roles:
    - { role: post_packstack_all, tags: post_packstack_all }

