#!/usr/bin/ansible-playbook
---
- hosts: [pxe]
  remote_user: root
  connection: local
  roles:
    - { role: generate_vars, tags: vars }    
    - { role: pxe, tags: pxe }    

# openstack prep
- hosts: [additional_compute]
  gather_facts: no
  roles:
    - { role: repave, tags: repave }
    - { role: expose_repos, tags: expose_repos }
    - { role: lab_custom, tags: lab_custom }
    - { role: prime_os, tags: prime_os }
    - { role: prepare_openstack, tags: prepare_openstack }
    - { role: change_kernel, tags: change_kernel }
    - { role: distribute_controller_key, tags: distribute_controller_key }
    - { role: hack_chkconfig, tags: hack_chkconfig }

- hosts: [controller]
  roles:
    - { role: install_openstack_for_additional_compute, tags: install_openstack_for_additional_compute }
    - { role: run_packstack_for_additional_compute, tags: run_packstack_for_additional_compute }

- hosts: [additional_compute]
  roles:
     - { role: unhack_chkconfig, tags: unhack_chkconfig }
     - { role: ovs_interfaces, tags: ovs_interfaces }
     - { role: post_packstack_nova, tags: post_packstack_nova }
     - { role: post_packstack_neutron_compute, tags: post_packstack_neutron_compute }
     - { role: post_packstack_all, tags: post_packstack_all }

