#!/usr/bin/ansible-playbook
---
- hosts: [controller]
  remote_user: root
  become: true
  roles:
    - { role: 20_generate_cloud_files, tags: 20_generate_cloud_files }

- hosts: [pxe]
  remote_user: root
  become: true
  connection: local
  roles:
    - { role: 20_prerequesites_installation, tags: 20_prerequesites_installation }
    - { role: 21_openstack_keystone       , tags: 21_openstack_keystone } 
    - { role: 22_openstack_glance           , tags: 22_openstack_glance }
    - { role: 23_openstack_neutron         , tags: 23_openstack_neutron }
    - { role: 24_secgroup_rules               , tags: 24_secgroup_rules }
    - { role: 25_openstack_nova_boot     , tags: 25_openstack_nova_boot }
#  environment:
#    http_proxy:
#    #no_proxy: 
#    no_proxy: 10.75.165.35,10.75.138.38

# to add a natted address to horizon as is the case in MVL
# sed -i '/^.*ServerAlias c00b00/a \  ServerAlias 100.65.194.202' /etc/httpd/conf.d/15-horizon_vhost.conf
# systemctl restart httpd
#- hosts: test_vm_group
#  roles:
#    - { role: 26_testing_connectivity        , tags: 26_testing_connectivity }
