#!/usr/bin/ansible-playbook
---
- hosts: [pxe]
  remote_user: root
  connection: local
  roles:
    - { role: generate_vars, tags: vars }    
    - { role: pxe, tags: pxe }    

# openstack prep
- hosts: [controller,compute]
  gather_facts: no
  roles:
    - { role: repave, tags: repave }
    - { role: expose_repos, tags: expose_repos }
    - { role: lab_custom, tags: lab_custom }
    - { role: prime_os, tags: prime_os }
    - { role: prepare_openstack, tags: prepare_openstack }
    - { role: change_kernel, tags: change_kernel }
