---
- name: Installing tftp-server
  yum: name=tftp-server state=present

- name: Installing syslinux
  yum: name=syslinux state=latest

- name: Enabling tftp under xinetd.d
  lineinfile:
    dest=/etc/xinetd.d/tftp
    regexp=disable
    line="        disable                 = no"
    state=present
 
- name: Restarting xinetd
  service: name=tftp state=started enabled=yes
  tags: tftp

- name: Creating tftp directory structure
  file: path=/var/lib/tftpboot/linux-install-x86_64/pxelinux.cfg state=directory

- name: Copying boot files to tftp dir
  command:  cp "{{ item.source }}" "{{ item.dest }}"
  with_items:
    - { source: '/stage/images/pxeboot/vmlinuz' ,    dest: '/var/lib/tftpboot/linux-install-x86_64/' }
    - { source: '/stage/images/pxeboot/initrd.img' , dest: '/var/lib/tftpboot/linux-install-x86_64/' }
    - { source: '/usr/share/syslinux/pxelinux.0' ,   dest: '/var/lib/tftpboot/linux-install-x86_64/' }

- name: Copying default boot file to tftp dir
  template: src=pxelinux.cfg.j2 dest=/var/lib/tftpboot/linux-install-x86_64/pxelinux.cfg/default

