---
- name: Loading Infrastructure File
  include_vars: "{{ playbook_dir }}/roles/generate_vars/vars/main.yml"
  tags: run_packstack
  
- name: Removing Http Proxy from bashrc to avoid "Bad Gateway" issue during Packstack
  lineinfile:
    dest=/root/.bashrc
    regexp="^export http_proxy.*$"
    state=absent
  tags: run_packstack
    
- name: Running Packstack
  shell: /usr/bin/packstack --answer-file="{{ packstack_dir }}/{{ packstack_answer_file }}" > "{{ packstack_output_file }}" 2>&1
  ignore_errors: yes
  register: packstack_run_for_additional_compute
  tags: run_packstack_for_additional_compute
  until: packstack_run_for_additional_compute.failed is not defined or packstack_run_for_additional_compute.failed == false
  retries: 10
  delay: 15
