---
# nova boot --flavor m1.medium --image testVMimage \
#           --nic net-id=$(docker-ostk neutron net-list| awk '/demo-vxlan-net/{print $2}')  \
#           --nic net-id=$(docker-ostk neutron net-list| awk '/ext-net/{print $2}')         \
#           --availability-zone nova bridge-vm1

  - name: Deleting Host VM1
    os_server:
      cloud: cloud-admin
      state: absent
      name: test-vm1
    register: vm1_deleted

  - name: Creating VM1 with Provider and Tenant network
    os_server:
      cloud: cloud-admin
      state: present
      name: test-vm1
      availability_zone: nova
      image: '{{ cloud_init_image }}'
      flavor: m1.medium
      security_groups: default
      auto_ip: no
      nics:
        - net-name: demo-vxlan-net
        - net-name: ext-net
    register: vm1_created
    when: vm1_deleted|success
    
  - name: Adding Host VM1
    add_host:
      name: '{{ vm1_created.openstack.name }}'
      groups: test_vm_group
      ansible_host: '{{ vm1_created.openstack.accessIPv4 }}'
      ansible_user: root
      ansible_ssh_pass: changeme
    register: vm1_added

  - name: Deleting Host VM2
    os_server:
      cloud: cloud-admin
      state: absent
      name: test-vm2
    register: vm2_deleted      

  - name: Creating VM2 with Tenant network and a floating IP
    os_server:
      cloud: cloud-admin
      state: present
      name: test-vm2
      availability_zone: nova
      image: '{{ cloud_init_image }}'
      flavor: m1.medium
      #security_groups: default
      auto_ip: yes
      nics:
        - net-name: demo-vxlan-net
    register: vm2_created
    
#  - debug: var=vm2_created
    
  - name: Adding Host VM2
    add_host:
      name: '{{ vm2_created.openstack.name }}'
      groups: test_vm_group
      ansible_host: '{{ vm2_created.openstack.accessIPv4 }}'
      ansible_user: root
      ansible_ssh_pass: changeme
    register: vm2_added

#  - name: Creating 200 VMs
#    shell: /tmp/many_vms.sh
#    tags: create_many_vms
   
#  - name: Waiting 3 minutes for the VMs to come up
#    pause: minutes=3      
