---
- name: De-exposing EPEL and RDO public repos
  yum: name={{ item }} state=absent
  with_items:
    - epel-release
    - rdo-release-{{ openstack_release }}

- name: Disabling Oracle Linux YUM Repo
  replace:
    dest: /etc/yum.repos.d/public-yum-ol7.repo
    regexp: '^enabled.*$'
    replace: 'enabled=0'

- name: create local repo directories 
  file: name=/rdolocal state=directory 

- name: mounting rdolocal dir
  mount: 
    name: /rdolocal
    state: mounted 
    src: "{{ hostvars['pxe']['ansible_host'] }}:/var/lib/repos/rdolocal"
    fstype: nfs 
    opts: defaults,soft
    dump: 0 
    passno: 2 

- name: create local epel/rdo-mitaka repos
  yum_repository:
    name: "rdolocal"
    state: present
    description: local rdolocal repo
    file: "rdolocal"
    baseurl: "file:///rdolocal/{{ openstack_release }}"
    gpgcheck: no
    enabled: yes
    priority: 1 

- name: clean yum
  command: yum clean all

- name: installing yum priorities plugin
  yum: name=yum-plugin-priorities state=present update_cache=yes

- name: enabling yum plugins
  ini_file:     
    dest: /etc/yum.conf     
    section: main  
    option: plugins  
    value: 1

