---
- name: De-exposing EPEL and RDO public repos
  yum: name={{ item }} state=absent
  with_items:
    - epel-release
    - rdo-release-{{ openstack_release }}

- name: create local repo directories /epel /rdo-mitaka
  file: name=/rdolocal state=directory 

- name: mounting rdolocal dir
  mount: 
    name: /rdolocal
    state: mounted 
    src: "{{ hostvars['pxe']['ansible_host'] }}:/var/lib/repos/rdolocal"
    fstype: nfs 
    opts: defaults,soft
    dump: 0 
    passno: 2 

- name: create local epel/rdo-mitaka repos
  yum_repository:
    name: "rdolocal"
    state: present
    description: local rdolocal repo
    file: "rdolocal.repo"
    baseurl: file:///rdolocal
    gpgcheck: no
    enabled: yes

#- name: Tryin epel repos by installing nmap    
#  yum: name=nmap state=installed
  
