---
#- debug: var=hostvars['pxe']['ansible_host']

- name: create local repo directories /epel /rdo-mitaka
  file: name={{ item }} state=directory 
  with_items:
    - /epel
    - /rdo-mitaka

- name: mount epel / rdo-mitaka local repos
  mount: 
    name: "/{{ item }}"
    state: mounted 
    src: "{{ hostvars['pxe']['ansible_host'] }}:/var/lib/repos/{{ item }}"
    fstype: nfs 
    opts: defaults,soft
    dump: 0 
    passno: 2 
  with_items:
    - epel
    - rdo-mitaka

- name: create local epel/rdo-mitaka repos
  yum_repository:
    name: "{{ item }}_local"
    state: present
    description: local {{ item }} repo
    file: "{{ item }}_local"
    baseurl: file:///{{ item }}
    gpgcheck: no
    enabled: yes
  with_items:
    - epel
    - rdo-mitaka

#- name: Tryin epel repos by installing nmap    
#  yum: name=nmap state=installed
  