---
 - name: loading infra file
   include_vars: "{{ playbook_dir }}/roles/generate_vars/vars/main.yml"
   
 - name: Creating provider network FLAT {{ infrastructure.vlans.openstack_provider_vlan.vlan_id }}
   os_network:
     cloud: cloud-admin
     state: present
     name: ext-net
     provider_network_type: flat
     provider_physical_network: physnet1
     shared: yes
     external: yes
   when: not infrastructure.vlans.openstack_provider_vlan.tagged_traffic_needed

 - name: Creating provider network VLAN {{ infrastructure.vlans.openstack_provider_vlan.vlan_id }}
   os_network:
     cloud: cloud-admin
     state: present
     name: ext-net
     provider_network_type: vlan
     provider_physical_network: physnet1
     provider_segmentation_id: '{{ infrastructure.vlans.openstack_provider_vlan.vlan_id }}'
     shared: yes
     external: yes
   when: infrastructure.vlans.openstack_provider_vlan.vlan_id is defined

 - name: Computing the subnet prefix
   shell: "/usr/bin/ipcalc -p '{{ infrastructure.vlans.openstack_provider_vlan.network }}' '{{ infrastructure.vlans.openstack_provider_vlan.netmask }}' | awk -F= '{print $2}'"
   register: prefix
     
# - debug: msg="{{ prefix.stdout }}"
     
 - name: Creating provider subnet
   os_subnet:
     cloud: cloud-admin
     state: present
     name: ext-subnet
     gateway_ip: '{{ infrastructure.vlans.openstack_provider_vlan.gateway }}'
     allocation_pool_start: '{{ infrastructure.vlans.openstack_provider_vlan.host_min }}'
     allocation_pool_end: '{{ infrastructure.vlans.openstack_provider_vlan.host_max }}'
     dns_nameservers: '{{ infrastructure.vlans.openstack_provider_vlan.name_server }}'
     enable_dhcp: False
     cidr: '{{ infrastructure.vlans.openstack_provider_vlan.network }}/{{ prefix.stdout }}'
     network_name: ext-net

 - name: Creating tenant network VxLAN
   os_network:
     cloud: cloud-admin
     state: present
     name: demo-vxlan-net
     provider_network_type: vxlan
     
 - name: Creating tenant subnet
   os_subnet:
     cloud: cloud-admin
     state: present
     name: demo-vxlan-subnet
     gateway_ip: 192.168.200.1
     allocation_pool_start: 192.168.200.2
     allocation_pool_end: 192.168.200.200
     enable_dhcp: False
     cidr: 192.168.200.0/24
     network_name: demo-vxlan-net
     

 - name: Creating Router
   os_router:
     cloud: cloud-admin
     state: present
     name: demo-vxlan-router
     interfaces: demo-vxlan-subnet
     network: ext-net
     
