#!/bin/ansible-playbook

- hosts: [127.0.0.1]
  connection: local
  gather_facts: no
  tasks:
  - include_vars: "{{ playbook_dir }}/roles/generate_vars/vars/main.yml"

  - set_fact: 
     image_dir: /var/lib/images/
     images:
        - name: MEATOS6.106.0
          url: http://10.240.121.66/images/MEATOS6.106.0
        - name: DSR-80_12_0.vmdk
          url: http://10.240.121.66/images/DSR/DSR-80_12_0.vmdk
     tenant: "admin"
     app_image: "DSR-80_12_0.vmdk"
     sshkey: 'dm'
     mp_count: 400
     heat_stack_name: DSR
     heat_yaml_template: /root/stack/stack.yaml
     heat_dir: /root/stack/
     heat_gen: /root/stack/dsr.generator.py
     #heat_stack_template: "/root/stack/"
    tags:
      - test 

  - name: grab images
    get_url:
        url="{{ item.url }}"
        dest="{{ image_dir }}"
    with_items:
      - "{{ images }}"

  - name: glance it
    os_image:
      cloud: "cloud-{{ tenant }}"
      name: '{{ item.name }}'
      container_format: bare
      disk_format: qcow2
      state: present
      filename: "{{ image_dir }}/{{ item.name }}"
    with_items:
      - "{{ images }}"

  - name: template heat stack yaml
    template: src="{{ heat_yaml_template }}" dest="{{ heat_dir }}{{ heat_stack_name }}.yaml"

  - name: create heat stack yaml
    lineinfile:
      "dest='{{ heat_dir }}{{ heat_stack_name }}.yaml'
      regexp='(.*){{ item.regex }}'
      backrefs=yes
      line='\\1{{ item.line }}'"
    with_items:
      - { regex: 'appimage',   line: 'image: {{ app_image }}'  }
      - { regex: 'ssh_key', line: 'ssh_key: {{ sshkey }}'   }
      - { regex: 'mpcount', line: 'mpcount: {{ mp_count }}' }

  - name: create heat stack template
    shell: "{{ heat_gen }} {{ heat_dir }}{{ heat_stack_name }}.yaml > {{ heat_dir }}{{ heat_stack_name }}.hot"
    tags:
      - test

  - name: setting quotas
    shell: "source /var/lib/openstack/keystonerc_*{{ tenant }}; openstack quota set --{{ item.name }} {{ item.value }} {{ tenant }}"
    with_items:
      - { name: server-group-members, value: -1 }
      - { name: instances,            value: -1 }
      - { name: cores,                value: -1 }
      - { name: ram,                  value: -1 }
      - { name: networks,             value: -1 }
      - { name: subnets,              value: -1 }
      - { name: ports,                value: -1 }
      - { name: floating-ips,         value: -1 }
    tags:
      - test

  - name: "start stack {{ heat_stack_name }}"
    shell: "source /var/lib/openstack/keystonerc_*{{ tenant }}; openstack stack create -t {{ heat_dir }}{{ heat_stack_name }}.hot {{ heat_stack_name }}"
    tags:
      - test

# 2.2 only pffft
#  - name: "start stack {{ heat_stack }}"
#    os_stack:
#      cloud: cloud-admin
#      state: present
#      template: "{{ heat_stack_template }}"
