---
  - name: Creating OpenStack Depot Directory
    file: path={{ image_file_dir }} state=directory mode=0755
    tags: fetching_cloudinit_image
     
  - name: Fetching cloud-init image
    get_url: url={{ image_url }} dest={{ image_file_dir }}/{{ image_file_name }} mode=0666 use_proxy=yes
    tags: fetching_cloudinit_image

  - name: Creating Image
    os_image:
      cloud: cloud-admin
      name: '{{ cloud_init_image }}'
      container_format: bare
      disk_format: qcow2
      state: present
      filename: "{{ image_file_dir }}/{{ image_file_name }}"
