---
- name: Removing hosts from host aggreggates
  shell: "source {{ openstack_dir }}/keystonerc_cloud_admin && /bin/openstack aggregate remove host {{ item.0.name }} {{ item.1.name }}"
  with_subelements:
    - "{{ host_aggregates }}"
    - hosts
  loop_control:
    label: "{{ item.0.name }}"
  register: host_aggregates_shell
  failed_when: "'failed' in host_aggregates_shell.stderr"
  changed_when: "host_aggregates_shell.rc == 0"

- name: Deleting host aggreggates
  shell: "source {{ openstack_dir }}/keystonerc_cloud_admin && /bin/openstack aggregate delete {{ item.name }}"
  with_items: "{{ host_aggregates }}"
  loop_control:
    label: "{{ item.name }}"
  ignore_errors: True
  register: host_aggregates_shell
  changed_when: "host_aggregates_shell.rc == 0"
  failed_when: "'ZZZzzzZZZ' in host_aggregates_shell.stderr"
