---
- name: ensure createrepo is installed
  yum: name=createrepo state=latest

###- name: Installing RDO Repo
###  yum: name=https://repos.fedorapeople.org/repos/openstack/openstack-{{ openstack_release }}/rdo-release-{{ openstack_release }}-5.noarch.rpm state=present
###
###- name: set permissions on repo directories
###  file: state=directory path=/var/lib/repos/rdolocal recurse=yes owner=root mode=0777
###
###- name: Downloading Packages
###  shell: "{{ playbook_dir }}/repo/packages.list"
###
###- name: createrepo /var/lib/repos/rdolocal
###  shell: createrepo /var/lib/repos/rdolocal

- name: setup nfs exports for epel and rdo-mitaka repos
  lineinfile:
    dest=/etc/exports
    state=present
    insertafter=EOF
    line="{{ item }}      *(ro,async)"
  with_items:
    - "/var/lib/repos"
  register: nfs_exports

- name: restart NFS
  service: name=nfs-server  state=restarted enabled=yes
  when: nfs_exports.changed
