---
- name: ensure createrepo is installed
  yum: name=createrepo state=latest

- name: create local repo dir /var/lib/repos
  file: path=/var/lib/repos/{{ item }}  state=directory owner=root mode=0777
  with_items:
    - epel
    - rdo-mitaka

#- name: wget mitaka repo
#  shell:  wget --mirror --no-parent --no-host-directories --timestamping --quiet --cut-dirs=5  --reject=index.html*,*\.css,*\.png,*\.gif,*.sh http://mirror.centos.org/centos/7/cloud/x86_64/openstack-mitaka
#
#- name: create local EPEL repo
#  shell:  wget --mirror --no-parent --no-host-directories --timestamping --quiet --cut-dirs=4  --reject=index.html*,*\.css,*\.png,*\.gif,*\.sh -X /pub/epel/7/x86_64/debug,/pub/epel/7/x86_64/repodata http://ftp.linux.ncsu.edu/pub/epel/7/x86_64/
#
#-name: add check for repodata dir before running below createrepo
#
#- name: createrepo /var/lib/repos/epel /var/lib/repos/rdo-mitaka
#  shell: createrepo /var/lib/repos/{{ item }}
#  with_items:
#    - epel
#    - rdo-mitaka
#

- name: set permissions on repo directories 
  file: state=directory path=/var/lib/repos recurse=yes owner=root mode=0777

- name: setup nfs exports for epel and rdo-mitaka repos
  lineinfile:
    dest=/etc/exports
    state=present
    insertafter=EOF
    line="{{ item }}      *(ro,async)"
  with_items:
    - "/var/lib/repos/epel"
    - "/var/lib/repos/rdo-mitaka"
  register: nfs_exports

- name: restart NFS
  service: name=nfs-server  state=restarted enabled=yes
  when: nfs_exports.changed
