SSHCMD="sshpass -p changeme ssh  -q -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
CMD="hostname"
CMD=$1
#CMD="pkill yum"
#IPMI="ipmitool -I lanplus -Uroot -Pchangeme chassis power cycle "
#CMD="yum install -y puppet hiera openssh-clients tar nc rubygem-json"
#CMD="rpm -q puppet hiera openssh-clients tar nmap-ncat rubygem-json"
#CMD="rpm -e mariadb-server-galera-1:10.1.12-4.el7.x86_64"
echo -en "\n - c00b00"; echo -en "  result --> "; r=$($SSHCMD c00b00 $CMD  || echo UNREACHABLE) ; printf "$r"  
echo -en "\n - c00b01"; echo -en "  result --> "; r=$($SSHCMD c00b01 $CMD  || echo UNREACHABLE);  printf "$r" 
echo -en "\n - c00b02"; echo -en "  result --> "; r=$($SSHCMD c00b02 $CMD  || echo UNREACHABLE) ; printf "$r"  
echo -en "\n - c00b03"; echo -en "  result --> "; r=$($SSHCMD c00b03 $CMD  || echo UNREACHABLE) ; printf "$r" 
echo -en "\n - c00b04"; echo -en "  result --> "; r=$($SSHCMD c00b04 $CMD  || echo UNREACHABLE) ; printf "$r" 
echo -en "\n - c00b05"; echo -en "  result --> "; r=$($SSHCMD c00b05 $CMD  || echo UNREACHABLE) ; printf "$r" 
echo -en "\n - c00b06"; echo -en "  result --> "; r=$($SSHCMD c00b06 $CMD  || echo UNREACHABLE) ; printf "$r" 
echo -en "\n - c00b07"; echo -en "  result --> "; r=$($SSHCMD c00b07 $CMD  || echo UNREACHABLE) ; printf "$r" 
echo -en "\n - c00b08"; echo -en "  result --> "; r=$($SSHCMD c00b08 $CMD  || echo UNREACHABLE) ; printf "$r" 
echo -en "\n - c00b09"; echo -en "  result --> "; r=$($SSHCMD c00b09 $CMD  || echo UNREACHABLE) ; printf "$r" 
echo -en "\n - c00b10"; echo -en "  result --> "; r=$($SSHCMD c00b10 $CMD  || echo UNREACHABLE) ; printf "$r" 
echo -en "\n - c00b11"; echo -en "  result --> "; r=$($SSHCMD c00b11 $CMD  || echo UNREACHABLE) ; printf "$r" 
echo
