#!/bin/ansible-playbook

- hosts: [localhost]
  connection: local
  gather_facts: no
  tasks:
  - include_vars: "{{ playbook_dir }}/site.yml"
    #- name: Loop through site
      #debug: msg="{{ item.key }} is {{ item.value.flavor }} ({{ item.value.networks }})"
      #with_dict: site1
