---
- name: load subnet variables
  include_vars: "{{ playbook_dir }}/group_vars/lab_specifics.yml"
  run_once: true

- include: add_flavors.yml
  when: state == 'present'

- include: del_flavors.yml
  when: state == 'absent'
