---
## FLAT based provider networks / subnets
- name: Deleting FLAT Admin/Provider Subnets
  os_subnet:
    cloud: cloud-admin
    state: "{{ state }}"
    name: "{{ item.1.name }}"
  with_subelements:
    - "{{ networks }}"
    - subnets
  when: item.0.provider_network_type == "flat"
  loop_control:
    label: "{{ item.1.name }}"

- name: Deleting FLAT Admin/Provider Networks
  os_network:
    cloud: cloud-admin
    state: "{{ state }}"
    name: "{{ item.name }}"
  when: item.provider_network_type == "flat"
  with_items: "{{ networks }}"
  loop_control:
    label: "{{ item.name }}"

## VLAN based provider networks / subnets
- name: Deleting VLAN Admin/Provider Subnets
  os_subnet:
    cloud: cloud-admin
    state: "{{ state }}"
    name: "{{ item.1.name }}"
  with_subelements:
    - "{{ networks }}"
    - subnets
  when: item.0.provider_network_type == "vlan"
  loop_control:
    label: "{{ item.1.name }}"

- name: Deleting VLAN Admin/Provider Networks
  os_network:
    cloud: cloud-admin
    state: "{{ state }}"
    name: "{{ item.name }}"
  when: item.provider_network_type == "vlan"
  with_items: "{{ networks }}"
  loop_control:
    label: "{{ item.name }}"
