---
- name: Generate ssh key
  user: name={{ user|default('root') }}  state=present generate_ssh_key=yes

- name: add host public key to authorized_keys
  authorized_key:
    user={{ user |default('root') }}
    state=present
    key="{{ lookup('file', "~/.ssh/id_rsa.pub") }}"

#- set_fact:
#    ssh_key: "{{ local_repo }}/master_root_ssh_key.pub"
#
#- name: check for master ssh key
#  become: false
#  local_action: stat path={{ ssh_key }} 
#  register: results
# 
#- name: add masters root ssh_key
#  authorized_key: user=root key="{{ lookup('file', \'{{ ssh_key }}\') }}"
#  when: results.stat.exists
#
