# 21_openstack_keystone
---
- name: Creating demo project
  os_project:
    cloud: cloud-admin
    state: present
    name: '{{ demo_tenant.name }}'
    description: '{{ demo_tenant.description }}'
    enabled: True

- name: Creating mgmt project
  os_project:
    cloud: cloud-admin
    state: present
    name: '{{ mgmt_tenant.name }}'
    description: '{{ mgmt_tenant.description }}'
    enabled: True
    
- name: Creating demoadmin user in demo project
  os_user:
    cloud: cloud-admin
    state: present
    name: '{{ demo_tenant.user }}'
    password: password
    default_project: '{{ demo_tenant.name }}'
    enabled: True
    
- name: Creating mgmtadmin user in mgmt project
  os_user:
    cloud: cloud-admin
    state: present
    name: '{{ mgmt_tenant.user }}'
    password: password
    default_project: '{{ mgmt_tenant.name }}'
    enabled: True
    
- name: Adding admin role to demoadmin
  shell: "source /var/lib/openstack/keystonerc_admin && openstack role add --project {{ demo_tenant.name }} --user {{ demo_tenant.user }} admin"
  ignore_errors: True
  register: command_result
  failed_when: "'FAILED' in command_result.stderr" 
  
- name: Adding admin role to mgmtadmin
  shell: "source /var/lib/openstack/keystonerc_admin && openstack role add --project {{ mgmt_tenant.name }} --user {{ mgmt_tenant.user }} admin"
  ignore_errors: True
  register: command_result
  failed_when: "'FAILED' in command_result.stderr" 
    
