---      
  - name: loading infra file
    include_vars: "{{ playbook_dir }}/roles/generate_vars/vars/main.yml"

  - name: Creating cloud files directory
    local_action: file path={{ openstack_dir }} state=directory mode=0755

  - name: Creating admin credential file
    local_action: template src=keystonerc_admin.j2 dest={{ openstack_dir }}/keystonerc_cloud_admin owner=root group=root mode=0755
    register: create_admin_rc

  - name: Creating demo credential file
    local_action: template src=keystonerc_demo.j2 dest={{ openstack_dir }}/keystonerc_cloud_demo owner=root group=root mode=0755
    register: create_demo_rc

  - name: Creating mgmt credential file
    local_action: template src=keystonerc_mgmt.j2 dest={{ openstack_dir }}/keystonerc_cloud_mgmt owner=root group=root mode=0755
    register: create_mgmt_rc

  - name: Creating clouds.yml locally
    local_action: template src=clouds.yml.j2 dest={{ playbook_dir }}/clouds.yml

  